# Generated by Django 5.0.10 on 2026-02-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payroll'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='absencerecord',
            new_name='core_absenc_person__3565ba_idx',
            old_name='core_absenc_person_start_idx',
        ),
        migrations.RenameIndex(
            model_name='absencerecord',
            new_name='core_absenc_status_f97fae_idx',
            old_name='core_absenc_status_start_idx',
        ),
        migrations.RenameIndex(
            model_name='accessevent',
            new_name='core_access_created_83a748_idx',
            old_name='core_accesse_created_fa4b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='accessevent',
            new_name='core_access_directi_808108_idx',
            old_name='core_accesse_directi_4d4b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='accessevent',
            new_name='core_access_person__5da79a_idx',
            old_name='core_accesse_person_i_4d1cd4_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='core_person_kind_403e90_idx',
            old_name='core_person_kind_87ee6e_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='core_person_tc_no_7940be_idx',
            old_name='core_person_tc_no_1ff2a8_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='core_person_phone_247ac1_idx',
            old_name='core_person_phone_812b4e_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='core_person_is_insi_aa6659_idx',
            old_name='core_person_is_ins_33c4c9_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='core_securi_plate_e21edc_idx',
            old_name='core_securi_plate_7b33f5_idx',
        ),
        migrations.RenameIndex(
            model_name='securitylog',
            new_name='core_securi_name_60f023_idx',
            old_name='core_securi_name_73b9c7_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='core_shifta_person__9a81f6_idx',
            old_name='core_shift_person_eff_idx',
        ),
        migrations.RenameIndex(
            model_name='shiftassignment',
            new_name='core_shifta_shift_i_146ad2_idx',
            old_name='core_shift_shift_eff_idx',
        ),
    ]
